language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  
services:
    memcached
    
before_script:
    # enable memcache in travis ci
    echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  
script: phpunit --bootstrap tests/bootstrap.php tests/MemoryCacheTest.php